<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
    <li><a href="https://#Section_1">Instructions</a></li>
    <li><a href="https://#Section_2">About the Data</a></li>
    <li><a href="https://#Section_3">Importing Data </a></li>
    <li><a href="https://#Section_4">Data Preprocessing</a> </li>
    <li><a href="https://#Section_5">One Hot Encoding </a></li>
    <li><a href="https://#Section_6">Train and Test Data Split </a></li>
    <li><a href="https://#Section_7">Train Logistic Regression, KNN, Decision Tree, SVM, and Linear Regression models and return their appropriate accuracy scores</a></li>
</a></li>
</div>
<p>Estimated Time Needed: <strong>180 min</strong></p>
</div>

<hr>


<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align="center"><font size="5">Final Project: Classification with Python</font></h1>


# Instructions


In this notebook, you will  practice all the classification algorithms that we have learned in this course.


Below, is where we are going to use the classification algorithms to create a model based on our training data and evaluate our testing data using evaluation metrics learned in the course.

We will use some of the algorithms taught in the course, specifically:

1. Linear Regression
2. KNN
3. Decision Trees
4. Logistic Regression
5. SVM

We will evaluate our models using:

1.  Accuracy Score
2.  Jaccard Index
3.  F1-Score
4.  LogLoss
5.  Mean Absolute Error
6.  Mean Squared Error
7.  R2-Score

Finally, you will use your models to generate the report at the end. 


# About The Dataset


The original source of the data is Australian Government's Bureau of Meteorology and the latest data can be gathered from [http://www.bom.gov.au/climate/dwo/](http://www.bom.gov.au/climate/dwo/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01).

The dataset to be used has extra columns like 'RainToday' and our target is 'RainTomorrow', which was gathered from the Rattle at [https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData](https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)




This dataset contains observations of weather metrics for each day from 2008 to 2017. The **weatherAUS.csv** dataset includes the following fields:

| Field         | Description                                           | Unit            | Type   |
| ------------- | ----------------------------------------------------- | --------------- | ------ |
| Date          | Date of the Observation in YYYY-MM-DD                 | Date            | object |
| Location      | Location of the Observation                           | Location        | object |
| MinTemp       | Minimum temperature                                   | Celsius         | float  |
| MaxTemp       | Maximum temperature                                   | Celsius         | float  |
| Rainfall      | Amount of rainfall                                    | Millimeters     | float  |
| Evaporation   | Amount of evaporation                                 | Millimeters     | float  |
| Sunshine      | Amount of bright sunshine                             | hours           | float  |
| WindGustDir   | Direction of the strongest gust                       | Compass Points  | object |
| WindGustSpeed | Speed of the strongest gust                           | Kilometers/Hour | object |
| WindDir9am    | Wind direction averaged of 10 minutes prior to 9am    | Compass Points  | object |
| WindDir3pm    | Wind direction averaged of 10 minutes prior to 3pm    | Compass Points  | object |
| WindSpeed9am  | Wind speed averaged of 10 minutes prior to 9am        | Kilometers/Hour | float  |
| WindSpeed3pm  | Wind speed averaged of 10 minutes prior to 3pm        | Kilometers/Hour | float  |
| Humidity9am   | Humidity at 9am                                       | Percent         | float  |
| Humidity3pm   | Humidity at 3pm                                       | Percent         | float  |
| Pressure9am   | Atmospheric pressure reduced to mean sea level at 9am | Hectopascal     | float  |
| Pressure3pm   | Atmospheric pressure reduced to mean sea level at 3pm | Hectopascal     | float  |
| Cloud9am      | Fraction of the sky obscured by cloud at 9am          | Eights          | float  |
| Cloud3pm      | Fraction of the sky obscured by cloud at 3pm          | Eights          | float  |
| Temp9am       | Temperature at 9am                                    | Celsius         | float  |
| Temp3pm       | Temperature at 3pm                                    | Celsius         | float  |
| RainToday     | If there was rain today                               | Yes/No          | object |
| RainTomorrow  | If there is rain tomorrow                             | Yes/No          | float  |

Column definitions were gathered from [http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml](http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)



## **Import the required libraries**


In [151]:
# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.
# !mamba install -qy pandas==1.3.4 numpy==1.21.4 seaborn==0.9.0 matplotlib==3.5.0 scikit-learn==0.20.1
# Note: If your environment doesn't support "!mamba install", use "!pip install"
!pip install -qy pandas==1.3.4 numpy==1.21.4 seaborn==0.9.0 matplotlib==3.5.0 scikit-learn==0.20.1


Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -y


In [152]:
# #you are running the lab in your  browser, so we will install the libraries using ``piplite``
# import piplite
# await piplite.install(['pandas'])
# await piplite.install(['numpy'])


In [153]:
import random 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.cluster import KMeans 
from sklearn.datasets import make_blobs 
%matplotlib inline

In [154]:
import numpy as np 
import pandas as pd

In [155]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics
from sklearn.metrics import r2_score

### Importing the Dataset


In [156]:
# from pyodide.http import pyfetch

# async def download(url, filename):
#     response = await pyfetch(url)
#     if response.status == 200:
#         with open(filename, "wb") as f:
#             f.write(await response.bytes())

In [157]:
import requests
from io import BytesIO

path='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv'
resp = requests.get(path)

# Make sure the request was successful
if resp.status_code == 200:
    text = BytesIO(resp.content)
    df = pd.read_csv(text)
    print('Data read into a pandas dataframe!')
else:
    print('Failed to fetch the data')

Data read into a pandas dataframe!


In [158]:
# path='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv'

In [159]:
# await download(path, "Weather_Data.csv")
# filename ="Weather_Data.csv"

In [160]:
# df = pd.read_csv("Weather_Data.csv")
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

### Data Preprocessing


#### One Hot Encoding


First, we need to perform one hot encoding to convert categorical variables to binary variables.


In [161]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])
df_sydney_processed

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0      2/1/2008     19.5     22.4      15.6          6.2       0.0   
1      2/2/2008     19.5     25.6       6.0          3.4       2.7   
2      2/3/2008     21.6     24.5       6.6          2.4       0.1   
3      2/4/2008     20.2     22.8      18.8          2.2       0.0   
4      2/5/2008     19.7     25.7      77.4          4.8       0.0   
...         ...      ...      ...       ...          ...       ...   
3266  6/21/2017      8.6     19.6       0.0          2.0       7.8   
3267  6/22/2017      9.3     19.2       0.0          2.0       9.2   
3268  6/23/2017      9.4     17.7       0.0          2.4       2.7   
3269  6/24/2017     10.1     19.3       0.0          1.4       9.3   
3270  6/25/2017      7.6     19.3       0.0          3.4       9.4   

      WindGustSpeed  WindSpeed9am  WindSpeed3pm  Humidity9am  ...  \
0                41            17            20           92  ...   
1                41             9            13           83  ...   
2                41            17             2           88  ...   
3                41            22            20           83  ...   
4                41            11             6           88  ...   
...             ...           ...           ...          ...  ...   
3266             37            22            20           73  ...   
3267             30            20             7           78  ...   
3268             24            15            13           85  ...   
3269             43            17            19           56  ...   
3270             35            13            13           73  ...   

      WindDir3pm_NNW  WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  \
0              False          False         False          False   
1              False          False         False          False   
2              False          False         False          False   
3              False          False         False          False   
4              False          False         False          False   
...              ...            ...           ...            ...   
3266           False          False         False          False   
3267           False          False         False          False   
3268           False          False         False          False   
3269           False          False         False          False   
3270           False          False         False          False   

      WindDir3pm_SSE  WindDir3pm_SSW  WindDir3pm_SW WindDir3pm_W  \
0              False            True          False        False   
1              False           False          False        False   
2              False           False          False        False   
3              False           False          False        False   
4              False           False          False         True   
...              ...             ...            ...          ...   
3266            True           False          False        False   
3267           False           False          False        False   
3268           False           False          False        False   
3269           False           False          False         True   
3270           False           False          False         True   

      WindDir3pm_WNW  WindDir3pm_WSW  
0              False           False  
1              False           False  
2              False           False  
3              False           False  
4              False           False  
...              ...             ...  
3266           False           False  
3267           False           False  
3268           False           False  
3269           False           False  
3270           False           False  

[3271 rows x 68 columns]

Next, we replace the values of the 'RainTomorrow' column changing them from a categorical column to a binary column. We do not use the `get_dummies` method because we would end up with two columns for 'RainTomorrow' and we do not want, since 'RainTomorrow' is our target.


In [162]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

### Training Data and Test Data


Now, we set our 'features' or x values and our Y or target variable.


In [163]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [164]:
df_sydney_processed = df_sydney_processed.astype(float)

In [165]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

### Linear Regression


#### Q1) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `10`.


In [166]:
X_train, X_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=10)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)


Train set: (2616, 66) (2616,)
Test set: (655, 66) (655,)


#### Q2) Create and train a Linear Regression model called LinearReg using the training data (`x_train`, `y_train`).


In [167]:
#Enter Your Code, Execute and take the Screenshot

In [168]:
LinearReg = LinearRegression()
LinearReg.fit (X_train, y_train)

LinearRegression()

#### Q3) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [169]:
#Enter Your Code, Execute and take the Screenshot

In [170]:
predictions = LinearReg.predict(X_test)
predictions[0:5]

array([0.13191986, 0.27619553, 0.97818375, 0.28746033, 0.13244629])

#### Q4) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [171]:
#Enter Your Code, Execute and take the Screenshot

In [172]:
LinearRegression_MAE = metrics.mean_absolute_error(y_test, predictions)
LinearRegression_MSE = metrics.mean_squared_error(y_test, predictions)
LinearRegression_R2 = metrics.r2_score(y_test , predictions)

print("Mean absolute error: %.2f" % LinearRegression_MAE)
print("Residual sum of squares (MSE): %.2f" % LinearRegression_MSE)
print("R2-score: %.2f" % LinearRegression_R2)

Mean absolute error: 0.26
Residual sum of squares (MSE): 0.12
R2-score: 0.43


#### Q5) Show the MAE, MSE, and R2 in a tabular format using data frame for the linear model.


In [173]:
#Enter Your Code, Execute and take the Screenshot

In [174]:
Report =  pd.DataFrame({
    'Metric': ['MAE', 'MSE', 'R^2'],
    'Value': [LinearRegression_MAE, LinearRegression_MSE, LinearRegression_R2]
})

# Display the DataFrame
Report

Metric     Value
0    MAE  0.256322
1    MSE  0.115723
2    R^2  0.427122

### KNN


#### Q6) Create and train a KNN model called KNN using the training data (`x_train`, `y_train`) with the `n_neighbors` parameter set to `4`.


In [175]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [176]:
KNN = KNeighborsClassifier(n_neighbors = 4).fit(X_train,y_train)
KNN

KNeighborsClassifier(n_neighbors=4)

#### Q7) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [177]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [178]:
# predictions = KNN.predict(X_test)
# predictions[0:5]

In [179]:
print(type(X_test))
X_test = X_test.to_numpy()
print(type(X_test))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [180]:
predictions = KNN.predict(X_test)
predictions[0:50]

array([0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.])

#### Q8) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [181]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [182]:
KNN_Accuracy_Score = metrics.accuracy_score(y_test, predictions)
KNN_JaccardIndex = jaccard_score(y_test, predictions,pos_label=0)
KNN_F1_Score = f1_score(y_test, predictions, average='weighted') 

print("Test set Accuracy: ", KNN_Accuracy_Score)
print("KNN_JaccardIndex: ", KNN_JaccardIndex)
print("KNN_F1_Score: ", KNN_F1_Score)

Test set Accuracy:  0.8183206106870229
KNN_JaccardIndex:  0.7901234567901234
KNN_F1_Score:  0.802374933635524


### Decision Tree


#### Q9) Create and train a Decision Tree model called Tree using the training data (`x_train`, `y_train`).


In [183]:
#Enter Your Code, Execute and take the Screenshot

In [184]:
Tree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
Tree.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

#### Q10) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [185]:
#Enter Your Code, Execute and take the Screenshot

In [186]:
predictions = Tree.predict(X_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

#### Q11) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [187]:
#Enter Your Code, Execute and take the Screenshot

In [188]:
Tree_Accuracy_Score = metrics.accuracy_score(y_test, predictions)
Tree_JaccardIndex = jaccard_score(y_test, predictions,pos_label=0)
Tree_F1_Score = f1_score(y_test, predictions, average='weighted') 

print("Tree_Accuracy_Score: ", Tree_Accuracy_Score)
print("Tree_JaccardIndex: ", Tree_JaccardIndex)
print("Tree_F1_Score: ", Tree_F1_Score)

Tree_Accuracy_Score:  0.8183206106870229
Tree_JaccardIndex:  0.781651376146789
Tree_F1_Score:  0.8132626923421479


### Logistic Regression


#### Q12) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `1`.


In [189]:
#Enter Your Code, Execute and take the Screenshot

In [190]:
X_train, X_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=1)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (2616, 66) (2616,)
Test set: (655, 66) (655,)


#### Q13) Create and train a LogisticRegression model called LR using the training data (`x_train`, `y_train`) with the `solver` parameter set to `liblinear`.


In [191]:
#Enter Your Code, Execute and take the Screenshot

In [192]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

#### Q14) Now, use the `predict` and `predict_proba` methods on the testing data (`x_test`) and save it as 2 arrays `predictions` and `predict_proba`.


In [193]:
#Enter Your Code, Execute and take the Screenshot

In [194]:
predictions = LR.predict(X_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

In [195]:
predict_proba = LR.predict_proba(X_test)
predict_proba

array([[0.71865901, 0.28134099],
       [0.97588318, 0.02411682],
       [0.49701338, 0.50298662],
       ...,
       [0.97264183, 0.02735817],
       [0.73341184, 0.26658816],
       [0.38535842, 0.61464158]])

#### Q15) Using the `predictions`, `predict_proba` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [196]:
#Enter Your Code, Execute and take the Screenshot

In [197]:
LR_Accuracy_Score = metrics.accuracy_score(y_test, predictions)
LR_JaccardIndex = metrics.jaccard_score(y_test, predictions,pos_label=0)
LR_F1_Score = f1_score(y_test, predictions, average='weighted') 
LR_Log_Loss = log_loss(y_test, predict_proba)

print("LR_Accuracy_Score: ", LR_Accuracy_Score)
print("LR_JaccardIndex: ", LR_JaccardIndex)
print("LR_F1_Score: ", LR_F1_Score)
print("LR_Log_Loss: ", LR_Log_Loss)

LR_Accuracy_Score:  0.8274809160305343
LR_JaccardIndex:  0.7941712204007286
LR_F1_Score:  0.8205451234161274
LR_Log_Loss:  0.3800846719164503


### SVM


#### Q16) Create and train a SVM model called SVM using the training data (`x_train`, `y_train`).


In [198]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [199]:
SVM = svm.SVC(kernel='rbf')
SVM.fit(X_train, y_train) 

SVC()

#### Q17) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [200]:
#Enter Your Code Below, Execute, and Save the Screenshot of the Final Output

In [201]:
predictions = SVM.predict(X_test)
predictions[0:5]

array([0., 0., 0., 0., 0.])

#### Q18) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [202]:
SVM_Accuracy_Score = metrics.accuracy_score(y_test, predictions)
SVM_JaccardIndex = jaccard_score(y_test, predictions,pos_label=0)
SVM_F1_Score = f1_score(y_test, predictions, average='weighted') 

print("SVM_Accuracy_Score: ", SVM_Accuracy_Score)
print("SVM_JaccardIndex: ", SVM_JaccardIndex)
print("SVM_F1_Score: ", SVM_F1_Score)

SVM_Accuracy_Score:  0.7221374045801526
SVM_JaccardIndex:  0.7221374045801526
SVM_F1_Score:  0.6056223268908018


### Report


#### Q19) Show the Accuracy,Jaccard Index,F1-Score and LogLoss in a tabular format using data frame for all of the above models.

\*LogLoss is only for Logistic Regression Model


In [203]:
Report = pd.DataFrame({
    'Model': ['KNN', 'Decision Tree', 'Logistic Regression', 'SVM'],
    'Accuracy Score': [KNN_Accuracy_Score, Tree_Accuracy_Score, LR_Accuracy_Score, SVM_Accuracy_Score],
    'Jaccard Index': [KNN_JaccardIndex, Tree_JaccardIndex, LR_JaccardIndex, SVM_JaccardIndex],
    'F1 Score': [KNN_F1_Score, Tree_F1_Score, LR_F1_Score, SVM_F1_Score],
    'Log Loss': ['N/A', 'N/A', LR_Log_Loss, 'N/A']  # Log Loss is applicable only for Logistic Regression
})

Report

Model  Accuracy Score  Jaccard Index  F1 Score  Log Loss
0                  KNN        0.818321       0.790123  0.802375       N/A
1        Decision Tree        0.818321       0.781651  0.813263       N/A
2  Logistic Regression        0.827481       0.794171  0.820545  0.380085
3                  SVM        0.722137       0.722137  0.605622       N/A

<h2 id="Section_5">  How to submit </h2>

<p>Once you complete your notebook you will have to share it. You can download the notebook by navigating to "File" and clicking on "Download" button.

<p>This will save the (.ipynb) file on your computer. Once saved, you can upload this file in the "My Submission" tab, of the "Peer-graded Assignment" section.  


<h2>About the Authors:</h2> 

<a href="https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01">Joseph Santarcangelo</a> has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

### Other Contributors

[Svitlana Kramar](https://www.linkedin.com/in/svitlana-kramar/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork30654641-2022-01-01)


## Change Log

| Date (YYYY-MM-DD) | Version | Changed By    | Change Description          |
| ----------------- | ------- | ------------- | --------------------------- |
| 2022-06-22        | 2.0     | Svitlana K.   | Deleted GridSearch and Mock |

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
